-- SQL Assignment 2
use mavenmovies;
-- Retrieve the total number of rentals made in the Sakila database
select count(rental_id) from rental;
-- Find the average rental duration (in days) of movies rented from the Sakila database
select * from film;
select avg(datediff(rental_date, return_date)) as Average_rental from rental;
-- Display the first name and last name of customers in uppercase
select upper(first_name) as Name, upper(last_name) as Surname from customer;
-- Extract the month from the rental date and display it alongside the rental ID
select * from rental;
select rental_id, month(rental_date) as Month_info from rental;
-- Retrieve the count of rentals for each customer (display customer ID and the count of rentals)
select * from customer;
select * from rental;
select customer_id, count(rental_id) from rental group by customer_id;
-- Find the total revenue generated by each staff
select * from staff;
select * from payment;
select staff_id, sum(amount) from payment group by staff_id;
-- Display the title of the movie, customer's first name, and last name who rented it
select * from film;
select * from inventory;
select * from rental;
select * from customer;
Select title as movie_title, first_name, last_name from film Inner join 
inventory on film.film_id = inventory.film_id Inner join 
rental on inventory.inventory_id = rental.inventory_id
Inner join customer on rental.customer_id = customer.customer_id;
-- Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
-- P.S- No movies found as "Gone with the Wind" therefore changed it with "Gone Trouble"
select * from film_actor;
select * from film;
select title from film where title = "Gone trouble";
select * from actor;
select first_name, last_name from actor;
select first_name, last_name from actor
Inner join film_actor on actor.actor_id = film_actor.actor_id
Inner join film on film_actor.film_id = film.film_id
where title = "Gone trouble";


